### ISSUE TITLE
Error opening .pbit file

### ISSUE THREAD

**Issue by ratson31** [microsoft/MicrosoftDefenderATP-PowerBI#3]
On opening the pbit and doing the initial refresh, this error appears

TVM_DeviceConfigurationAssesmentKB
The column 'RelatedMitreTechniques' of the table wasn't found.

**Comment by richlilly2004** [comment]
You can open "Transform Data", Select TVM_DeviceConfigurationAssesmentKB, Advanced Editor, and remove the following rows (including the trailing comma):

,
    #"Expanded RelatedMitreTechniques" = Table.ExpandListColumn(#"Expanded ConfigurationBenchmarks", "RelatedMitreTechniques"),
    #"Expanded RelatedMitreTactics" = Table.ExpandListColumn(#"Expanded RelatedMitreTechniques", "RelatedMitreTactics")

and replace #"Expanded RelatedMitreTactics" at the bottom with Table"
